Crowdfund.Web/Controllers/BackerController.cs
using System.Threading.Tasks;
using Autofac;
using CrowdfundCore;
using CrowdfundCore.Data;
using CrowdfundCore.Services;
using Microsoft.AspNetCore.Mvc;

namespace Crowdfund.Web.Controllers
{
    public class BackerController : Controller
    {
        private IContainer Container { get; set; }
        private CrowdfundDbContext context_;
        private IBackerService backers_;

        public BackerController()
        {
             Container = ServiceRegistrator.GetContainer();
             context_ = Container.Resolve<CrowdfundDbContext>();
             backers_ = Container.Resolve<IBackerService>(); ;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]  
        public async Task<IActionResult> Create(
                Models.CreateBackerViewModel model)
        {
            var result = await backers_.AddBackerAsync(
                model?.AddBackerOptions);

            if (result == null) {
                model.ErrorText = "Oops. Something went wrong";
                return View(model);
            }

            return Ok();


        }
    }
}

Crowdfund.Web/Controllers/ProjectController.cs
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using Autofac;
using Crowdfund.Web.Extensions;
using Crowdfund.Web.Models;
using CrowdfundCore;
using CrowdfundCore.Data;
using CrowdfundCore.Services;
using Microsoft.AspNetCore.Mvc;

namespace Crowdfund.Web.Controllers
{
    public class ProjectController : Controller
    {
        private IContainer Container { get; set; }
        private CrowdfundDbContext context_;
        private CrowdfundCore.Services.IProjectService project_;

        public ProjectController()
        {
            Container = ServiceRegistrator.GetContainer();
            context_ = Container.Resolve<CrowdfundDbContext>();
            project_ = Container.Resolve<IProjectService>();
        }


        public IActionResult Index()
        {
            var projectList = context_
                .Set<Project>()
                .Take(100)
                .ToList();

            return View(projectList);
        }


        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
         
        [HttpGet]
        public IActionResult Search()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Search(
           [FromBody] Models.SearchProjectViewModel model)
        {
            var result = project_.SearchProjectsAsync(
                model?.SearchProjectOptions)
                .Select(p => new {
                    title = p.Title,
                    budget = p.budget,
                    deadline = p.Deadline.ToString("dd/MM/yyyy"),
                    detailsUrl = Url.Action("detail", "project", new { id = p.Id })
                })
                .ToList();

            return Json(result);
        }

        [HttpGet("project/{id}")]
        public IActionResult Detail(int id)
        {
            var project = context_.Set<Project>()
                .Where(p => p.Id == id)
                .Include(p => p.Rewards)
                .SingleOrDefault();

            var model = new DetailViewModel()
            {
                Project = project,
                Context = context_
            };

            return View(model);
        }

        [HttpGet("project/title/{title}")]
        public IActionResult Detail(string title)
        {
            var project = context_.Set<Project>()
                .Where(p => p.Title.Contains(title));
            return View(project);
        }

        [HttpGet("project/budget/{budget}")]
        public IActionResult Detail(decimal budget)
        {
            var project = context_.Set<Project>()
                .Where(p => p.budget<budget);
            return View(project);
        }

        [HttpPost]
        public async Task<IActionResult> Create(
            [FromBody] Models.CreateProjectViewModel model)
        {
            model.CreateProjectOptions.Rewards = model.Rewards;

            var result = await project_.CreateProjectAsync(
                model?.CreateProjectOptions);
            
            if (!result.Success) {
                return result.AsStatusResult();
            }

            return Json(new {
                id = result.Data.Id
            });
        }
    }
}

Crowdfund.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Crowdfund.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>

        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Crowdfund</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Project" asp-action="Index">Projects</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Project" asp-action="Create">Create Project</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Backer" asp-action="Create">Sign up as a backer</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Project" asp-action="search">Search Project</a>
                        </li>
                    </ul>
                </div>
            </div>   
            <form class="navbar-form navbar-left" action="/action_page.php">
            <div class="input-group">
                <input type="text" class="form-control" placeholder="Search">
                <div class="input-group-btn">
                    <button class="btn btn-default" type="submit">
                        <i class="glyphicon glyphicon-search"></i>
                    </button>
                </div>
            </div>
        </form>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
        @*<nav class="navbar navbar-light bg-light">
            <form class="form-inline">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit" asp-area="" asp-controller="Project" asp-action="Search">Search</button>
            </form>
        </nav>*@

        @*<div class="list-group">
            <button type="button" class="list-group-item list-group-item-action active">
               Project List
            </button>
            <button type="button" class="list-group-item list-group-item-action">Title</button>
            <button type="button" class="list-group-item list-group-item-action">Description</button>
            <button type="button" class="list-group-item list-group-item-action">Name</button>
            <button type="button" class="list-group-item list-group-item-action">Budget</button>
        </div>*@

        @*<img src="~/NewFolder/Crowdfunding.jpg" alt="Flowers in Chania">*@
        @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Crowdfund.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Pivacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>